sonar.projectKey=devops
sonar.projectName=devops
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**

sonar.host.url=http://localhost:9000

sonar.login= sqp_6aec6af2e75b2990f53f7529b65cbd1d721c494f